### ISSUE TITLE
Provision fails on Ubuntu

### ISSUE THREAD

**Issue by snoek09** [AmsterdamPHP/amsterdamphp.nl#78]
The provision fails on Ubuntu 14.04 because the user doesn't have the right permissions.
This is caused by missing linux nfs options in the vagrant config.

```
TASK: [App | Populate parameters.yml] ***************************************** 
failed: [default] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-rwigpxqezqtxklvgutkrzykpxnykvwam
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1417431937.94-243284657440523/copy", line 1595, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1417431937.94-243284657440523/copy", line 228, in main
    module.atomic_move(src, dest)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1417431937.94-243284657440523/copy", line 1411, in atomic_move
    os.chown(dest, os.getuid(), os.getgid())
OSError: [Errno 1] Operation not permitted: '/var/www/amsphp/app/config/parameters.yml'
Exception OSError: (2, 'No such file or directory', '/var/www/amsphp/app/config/.ansible_tmptBCwA_parameters.yml') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0xff9030>> ignored
```

**Comment by dennisdegreef** [comment]
Can this issue also be closed? The pull request states:
`snoek09 closed this on Jan 6`

Has the the problem been resolved?

**Comment by snoek09** [comment]
Problem is still there, will re-open PR.

**Comment by dennisdegreef** [comment]
If it helps, I would be able to test this on monday, i'll then have access to a (graphical) Linux machine :)
